<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AMJ</title>

    <!-- CSS -->
    <link rel="stylesheet" href="<?=BASE_URL?>/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?=BASE_URL?>/assets/css/font-awesome.min.css">

    <!-- JS -->
    <script src="<?=BASE_URL?>/assets/js/jquery-3.4.1.slim.min.js"></script>
    <script src="<?=BASE_URL?>/assets/js/popper.min.js"></script>
    <script src="<?=BASE_URL?>/assets/js/bootstrap.min.js"></script>
    <script src="<?=BASE_URL?>/assets/js/sweetalert2@9.js"></script>
</head>
</html>