<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">AMJ</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#">Fornecedores</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Clientes</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Valores</a>
        </li>
    </ul>
</nav>