<?php include 'templates/navbar.phtml'; ?>

<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card mt-3 py-0">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-11">
                                <h4 class="card-title">
                                    Fornecedores
                                    <small>(responsáveis pelo fornecimento das peças para reparo)</small>
                                </h4>
                            </div>
                            <div class="col-1 text-right">
                                <button class="btn btn-success font-weight-bold pull-right">+</button>
                            </div>
                        </div>
                    </div>
                    <div class="card-block">
                        <table class="table table-bordered m-0">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">CNPJ</th>
                                    <th scope="col">Razão Social</th>
                                    <th scope="col">Contratos</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th scope="row">1</th>
                                    <td>Mark</td>
                                    <td>Otto</td>
                                    <td>0 Contratos</td>
                                </tr>
                                    <tr>
                                    <th scope="row">2</th>
                                    <td>Jacob</td>
                                    <td>Thornton</td>
                                    <td>0 Contratos</td>
                                </tr>
                                <tr>
                                    <th scope="row">3</th>
                                    <td>Larry</td>
                                    <td>the Bird</td>
                                    <td>0 Contratos</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<?php include 'templates/footer.phtml'; ?>